---
title: "check in 3"
author: "damian rojas"
format: pdf
date: 2026-05-28
---

## Set-up
```{r,message=FALSE}
library(tidyverse)
library(ggeffects)
library(janitor)
library(ggplot2)
library(dplyr)
library(plotly)
library(viridis)
library(hrbrthemes)
library(ggbeeswarm)
#beeswarm package from failed beeswarm plot

```

## Read in data from personal data project


```{r, message=FALSE}
walks <- read.csv("walks_data.csv") |> 
#from HW 2
mutate(work_due = as_factor(work_due))
       #factor so data is listed in order of appearance, cleans up repeats
#create graph, start with gg plot as base layer
# x = categorical predictor
ggplot(walks, aes(x = work_due, 
# y = response variable (in seconds to avoid graph looking skewed)
                  y = walk_time_s)) +
# scatter plot to compare relationship between predictor and response variable
geom_jitter(height = 0,
            width = 0,
            shape = 16,
            size=5,
            color="red3") +
                        
#label graph
labs(title="Workload vs Walk time", 
     x = "Assignments due",
     y = "Length of walk (sec)") +
#change theme
theme_gray()

```

```{r, message=FALSE}
#from HW2 to show potential relationship between degrees and walk time
#collect personal data
walks |> 

mutate(WEATHER_F = as_factor(WEATHER_F))

#create graph, start with gg plot as base layer
#x=continuous predictor, weather
#y= length of walk
#take degrees F ofdatqa sheet, abel in axis
ggplot(walks, aes(x = WEATHER_F, 
                  y = walk_time_s)) +
#scatter plot to compare relationship between continuous predictor and response 
geom_point(color="orange4", size = 5) +

#label graph
labs(title = "Weather vs Walk Time", 
     x = "Weather(°F)", 
     y = "Length of Walk (sec)") +

#change theme
theme_bw()
```

## Attempting new visualization (hexbin)

```{r, message=FALSE}
#hexbin plot

#base ggplot, dataset = walks
#x stored as numeric factor form work due
#y = walk time in seconds
ggplot(walks, aes(x =as.numeric(as.character (work_due)), y = walk_time_s)) +
  #hexbin geometry frmo ggplot2
  #bins = 16 for gut-check
  geom_hex(bins = 16) +
  #set gradient fill from light blue (low) to dark blue for high values
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  theme_minimal() 
#doesnt look great try something else
```

## Attempting new visualization (bubblechart)

```{r, message=FALSE}
#walks data
walks |> 
  #arrange data by descinging order for work due
  arrange(desc(work_due)) |> 
#store work due as numeric value instead of factor
  mutate(work_due = as.numeric(as.character(work_due))) |> 
  #base ggplot, x = work due, y = walk time in seconds
  ggplot(aes(x=work_due, y = walk_time_s, size = work_due, color = work_due)) +
  #geom point for bubblechart shape
  geom_point(alpha=0.5) +
  #scale by work due,
  scale_size(range = c(10,24), name ="Work Due")
  
```

## Attempting new visualization
(violin plot)

```{r, message=FALSE}

walks |>
  #mutate work_due as a factor
  mutate(work_due = factor(work_due)) |>
  #base gg plot
  ggplot(aes(
    # x = work due
    x = work_due,
    #y is walk time in seconds
    y = walk_time_s,
    #color by work due
    color = work_due
  )) +
  #violin plot geometry
  geom_violin(
    #thickness of lines
    linewidth = 1,
    #drop equal false to not drop data sets with fewer than 2 values
 drop = FALSE ) +
#set color by work due
  scale_color_viridis_d("work_due") +
  theme_minimal()
```

